drop table if exists likes cascade;
drop table if exists user_role cascade;
drop table if exists users cascade;
drop table if exists users_comments cascade;
drop sequence if exists hibernate_sequence;
create sequence hibernate_sequence start 1 increment 1;
create table comics (id int8 not null, artist varchar(255), description varchar(255), filename1 varchar(255) not null, filename2 varchar(255), filename3 varchar(255), hyperlink_eng varchar(255), hyperlink_ru varchar(255), publisher varchar(255) not null, screenwriter varchar(255), title varchar(255) not null, year varchar(255), likes_id int8, primary key (id));
create table comments (id int8 not null, created_at timestamp not null, text varchar(255), user_id int8, comic_id int8, primary key (id));
create table favourites (id int8 not null, user_id int8, comic_id int8, primary key (id));
create table likes (id int8 not null, impression_mark varchar(255), picture_mark varchar(255), plot_mark varchar(255), primary key (id));
create table user_role (user_id int8 not null, roles varchar(255));
create table users (id int8 not null, active boolean not null, password varchar(255), username varchar(255), primary key (id));
create table users_comments (user_id int8 not null, comments_id int8 not null, primary key (user_id, comments_id));
alter table users_comments add constraint UK_8a9ff54pt2w205r0hlcbe8mm6 unique (comments_id);
alter table comics add constraint FKsvi230blophw1bos6dilsc9f6 foreign key (likes_id) references likes on delete cascade;
alter table comments add constraint FK8omq0tc18jd43bu5tjh6jvraq foreign key (user_id) references users on delete cascade;
alter table comments add constraint FKmhr5rshgbg9tgcp2brwb2065j foreign key (comic_id) references comics on delete cascade;
alter table favourites add constraint FK6ffqdnwmm3ks4fenx2ml1uap8 foreign key (user_id) references users on delete cascade;
alter table favourites add constraint FKilo23y2hb6toiv0qm4vh63jt6 foreign key (comic_id) references comics on delete cascade;
alter table user_role add constraint FKj345gk1bovqvfame88rcx7yyx foreign key (user_id) references users;
alter table users_comments add constraint FK3b83nq9ncocq7tb4e90dyqmqg foreign key (comments_id) references comments;